name = "numeric_simulation"
version = "0.1.0"
license = "GPL-3.0"
author = "osada-yum"
maintainer = "osada.yum@gmail.com"
copyright = "Copyright 2023, osada-yum"
[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false
external-modules = ["mpi"]
[install]
library = true
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

